[project]
name = "jetweb"
version = "0.1.0"
description = "Lightweight Python WSGI-compatible web framework"
authors = [
    {name = "Nazarii Kuntsevych", email = "kuntsevych.n.v@gmail.com"},
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
